Added MolarMass, MolarVolume, InverseToMolarMass, and some extra Densities
ferraridamiano/units_converter pull request #33
Opened 2022-12-10 04:44 UTC by Dokotela

Added new properties
- MOLAR_MASS
- INVERSE_OF_MOLAR_MASS
- MOLAR_VOLUME

I also added some more densities. 

I've added tests for all of the above, but some of the conversion tests for MOLAR_VOLUME don't quite work the way I want them to. For instance:
MOLAR_VOLUME.nanoMolesPerMilliLiter: 999999.9999999999
But should be:
MOLAR_VOLUME.nanoMolesPerMilliLiter: 1000000

Any recommendations on where I went wrong?

2022-12-10 15:03 UTC, ferraridamiano commented
Hi @Dokotela and thank you for another wonderful PR! I'm going to review it and commit if needed! Don't worry too much about that calculations problem. Hope to finish the review today

2022-12-10 15:45 UTC, ferraridamiano requested changes
I submitted a cuple of commit in order to make the CI happy. The PR looks good. Most of the units name should be changed to be coherent with the other unit names (explained in a comment).

Now just a curiosity, is "reciprocal of molar mass" actually used in chemistry? Or is it something specific of your application?

Thank you again!

2022-12-10 15:45 UTC, ferraridamiano commented on lib/properties/density.dart
> +  picoGramsPerMilliLiter(MASS.picograms, VOLUME.milliliters),
Make these names more coherent. If a unit is written in muliple parts write them with camelCase
e.g. "milligrams per liter" -> milligramsPerLiter

2022-12-10 15:45 UTC, ferraridamiano commented on lib/properties/density.dart
> +  Unit get picoGramsPerMilliLiter => getUnit(DENSITY.picoGramsPerMilliLiter);
The same naming convention should also be applied here

2022-12-10 15:45 UTC, ferraridamiano commented on lib/properties/molar_mass.dart
> +  kiloGramsPerMilliMole(MASS.kilograms, AMOUNT_OF_SUBSTANCE.millimoles),
Also here

2022-12-10 15:45 UTC, ferraridamiano commented on lib/properties/molar_mass.dart
> +  Unit get kiloGramsPerMilliMole => getUnit(MOLAR_MASS.kiloGramsPerMilliMole);
And here

2022-12-10 15:45 UTC, ferraridamiano commented on lib/properties/molar_volume.dart
> +  femtoMolesPerMilliLiter(AMOUNT_OF_SUBSTANCE.femtomoles, VOLUME.milliliters),
Here

2022-12-10 15:45 UTC, ferraridamiano commented on lib/properties/molar_volume.dart
> +      getUnit(MOLAR_VOLUME.femtoMolesPerMilliLiter);
Here

2022-12-10 15:45 UTC, ferraridamiano commented on lib/properties/molar_volume.dart
> +  ///print(MOLAR_VOLUME.kilogramsPerLiter);
The example refers to density

2022-12-10 15:45 UTC, ferraridamiano commented on lib/properties/molar_mass.dart
> +  ///print(MOLAR_MASS.kilogramsPerLiter);
The example refers to density

2022-12-10 15:45 UTC, ferraridamiano commented on lib/properties/reciprocal_of_molar_mass.dart
> +  ///print(RECIPROCAL_OF_MOLAR_MASS.kilogramsPerLiter);
Update the example

2022-12-10 15:45 UTC, ferraridamiano commented on lib/properties/reciprocal_of_molar_mass.dart
> +    RECIPROCAL_OF_MOLAR_MASS.milliMolesPerKiloGram: 'mmol/kg',
Also here

2022-12-10 15:45 UTC, ferraridamiano commented on lib/properties/reciprocal_of_molar_mass.dart
> +      getUnit(RECIPROCAL_OF_MOLAR_MASS.milliMolesPerKiloGram);
And here

2022-12-11 03:34 UTC, Dokotela commented
Above recommendations should be fixed. 

Reciprocal of molar mass isn't used in normal chemistry (at least I haven't seen it), but is used in medicine. 

If a patient needs 12 mmol of something, and the medication comes in 3 mmol/gram, you need to order 4 grams. Obviously a simple example.

2022-12-11 10:23 UTC, merged

2022-12-11 10:24 UTC, ferraridamiano commented
Perfect, thank you very much @Dokotela! I will soon publish a new release with all your new units!